version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tracy-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - tracy_db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: tracy-api
    ports:
      - '3050:3050'
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  tracy_db_data:
